### ISSUE TITLE
Revision For 'howManyParks.js' --> 'HowManyParks.js' To Fulfill React Standard Function Naming Convention

### ISSUE THREAD

**Issue by SamuelBanya** [learn-co-curriculum/react-hooks-import-export#15]
### Canvas Link

https://learning.flatironschool.com/courses/5285/assignments/172389?module_item_id=376286

### Concern

Shouldn't 'howManyParks'.js' be capitalized to 'HowManyParks.js' as well as the function name itself, 'howManyParks' --> 'HowManyParks' to fulfill the React standard principle?

**Comment by professor-ben** [comment]
Hi Samuel,

JavaScript and React naming conventions aren't quite as strict as they are with languages like Java and Python. With vanilla JS (no React), we use camelCase. PascalCase for React.

Thank you,
Ben
