### ISSUE TITLE
Proper punctuation for auditory learning, please. Even when it isn't strictly necessary.

### ISSUE THREAD

**Issue by gmd298** [learn-co-curriculum/react-hooks-import-export#9]
### Canvas Link

https://learning.flatironschool.com/courses/5172/assignments/172414

### Concern

I use text to voice when I go through lessons. Not having proper punctuation makes the content confusing and less accessible.

I put a reference to what I am talking about in the Additional Context field. I assume because you are using bullet points that means you dont need to use periods. I have seen that plenty of times before. But, like I mentioned above, it makes the content confusing for anyone who also uses text to voice. Like, why even use commas if you aren't even going to put a period at the end of the statement? 

### Additional Context

"

- Stricter variable scope: Variables declared in modules are private unless they are explicitly exported, so by using modules, you don't have to worry about polluting the global variable scope
- Single-responsibility principle: Each module is responsible for accomplishing a certain piece of functionality, or adding a specific feature to the application
- Easier to navigate: Modules that are separated and clearly named make code more readable for other developers
- Easier to debug: Bugs have less room to hide in isolated, contained code
- Produce clean and DRY code: Modules can be reused and repurposed throughout applications

"

### Suggested Changes

Just use proper punctuation, even if you don't think it is necessary. It makes the content more accessible to people who lean more towards auditory learning.

**Comment by lizbur10** [comment]
Hi @gmd298 ! Thank you for bringing this to our attention! This issue has been added to our accessibility documentation, and the corrections have been made in this lesson. The change will also be implemented in other lessons as they are updated and revised. In the meantime, if you see other examples of the problem, feel free to post issues for those as well so we can address them more quickly.

Thanks for contributing to the Flatiron School curriculum 💙
